"""add_version_2_tables

Revision ID: 3e01201308cd
Revises: 392713c6803a
Create Date: 2026-06-17 00:29:32.726577

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3e01201308cd'
down_revision: Union[str, None] = '392713c6803a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dedup_groups',
    sa.Column('id', sa.String(length=50), nullable=False),
    sa.Column('group_type', sa.String(length=50), nullable=False),
    sa.Column('canonical_result_id', sa.String(length=50), nullable=True),
    sa.Column('canonical_url', sa.Text(), nullable=False),
    sa.Column('content_hash', sa.String(length=64), nullable=True),
    sa.Column('simhash', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('entities',
    sa.Column('id', sa.String(length=50), nullable=False),
    sa.Column('canonical_name', sa.String(length=255), nullable=False),
    sa.Column('entity_type', sa.String(length=100), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('official_url', sa.Text(), nullable=True),
    sa.Column('wikidata_id', sa.String(length=50), nullable=True),
    sa.Column('wikipedia_url', sa.Text(), nullable=True),
    sa.Column('openalex_id', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_entities_wikidata_id'), 'entities', ['wikidata_id'], unique=False)
    op.create_table('entity_aliases',
    sa.Column('id', sa.String(length=50), nullable=False),
    sa.Column('entity_id', sa.String(length=50), nullable=False),
    sa.Column('alias', sa.String(length=255), nullable=False),
    sa.Column('language', sa.String(length=10), nullable=True),
    sa.Column('valid_from', sa.DateTime(), nullable=True),
    sa.Column('valid_to', sa.DateTime(), nullable=True),
    sa.Column('source', sa.String(length=50), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['entity_id'], ['entities.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('dedup_members',
    sa.Column('id', sa.String(length=50), nullable=False),
    sa.Column('group_id', sa.String(length=50), nullable=False),
    sa.Column('result_id', sa.String(length=50), nullable=False),
    sa.Column('match_type', sa.String(length=50), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['group_id'], ['dedup_groups.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['result_id'], ['normalized_results.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('entity_links',
    sa.Column('id', sa.String(length=50), nullable=False),
    sa.Column('entity_id', sa.String(length=50), nullable=False),
    sa.Column('result_id', sa.String(length=50), nullable=False),
    sa.Column('document_id', sa.String(length=50), nullable=True),
    sa.Column('mention', sa.String(length=255), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('decision', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['entity_id'], ['entities.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['result_id'], ['normalized_results.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('quality_scores',
    sa.Column('id', sa.String(length=50), nullable=False),
    sa.Column('result_id', sa.String(length=50), nullable=False),
    sa.Column('relevance_score', sa.Float(), nullable=True),
    sa.Column('source_reliability_score', sa.Float(), nullable=True),
    sa.Column('freshness_score', sa.Float(), nullable=True),
    sa.Column('authority_score', sa.Float(), nullable=True),
    sa.Column('entity_match_score', sa.Float(), nullable=True),
    sa.Column('dedup_confidence', sa.Float(), nullable=True),
    sa.Column('extraction_likelihood_score', sa.Float(), nullable=True),
    sa.Column('risk_score', sa.Float(), nullable=True),
    sa.Column('final_trust_score', sa.Float(), nullable=True),
    sa.Column('decision', sa.String(length=50), nullable=True),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['result_id'], ['normalized_results.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('quality_scores')
    op.drop_table('entity_links')
    op.drop_table('dedup_members')
    op.drop_table('entity_aliases')
    op.drop_index(op.f('ix_entities_wikidata_id'), table_name='entities')
    op.drop_table('entities')
    op.drop_table('dedup_groups')
    # ### end Alembic commands ###
